Add SpeedTest module
hak5/mk7-modules pull request #39
Opened 2021-05-20 16:33 UTC by TW-D

2021-06-16 12:02 UTC, foxtrot commented on speedtest/projects/speedtest/src/lib/components/speedtest.component.html
> +                    <b>Connected</b> : {{ (network_connected) ? 'OK' : 'NOK' }}
NOK?

2021-06-16 12:02 UTC, foxtrot commented on speedtest/projects/speedtest/src/lib/components/speedtest.component.html
> +                    <b>python3-pip</b> : {{ (dependency_python3_pip) ? 'OK' : 'NOK' }}
NOK?

2021-06-16 12:03 UTC, foxtrot requested changes
Please fix typos

2021-06-17 07:46 UTC, TW-D commented on speedtest/projects/speedtest/src/lib/components/speedtest.component.html
> +                    <b>Connected</b> : {{ (network_connected) ? 'OK' : 'NOK' }}
Corrected

2021-06-17 07:46 UTC, TW-D commented on speedtest/projects/speedtest/src/lib/components/speedtest.component.html
> +                    <b>python3-pip</b> : {{ (dependency_python3_pip) ? 'OK' : 'NOK' }}
Corrected

2021-07-08 18:38 UTC, closed without merging